title: Policy Nexus
description: Documentation for the Policy Nexus Project.



theme: just-the-docs

repository: https://github.com/policynexus/documentation

url: https://docs.policynexus.eu/

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


back_to_top: true
back_to_top_text: "Back to top"
footer_content: 'Copyright &copy; 2024 Policy Nexus <br /> <a href="/pages/impressum.html" >Impressum</a> | <a href="/pages/privacy.html">Privacy Policy</a>'